<a href="https://colab.research.google.com/github/uto4ka101/First/blob/main/data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/data.csv',encoding='utf-8').drop(columns=['Unnamed: 0', 'id', 'key']).set_index(['artists', 'name']) 
data.head()

                                                                                                       acousticness  ...  year
artists                                            name                                                              ...
['Dennis Day']                                     Clancy Lowered the Boom                                    0.732  ...  1921
['Sergei Rachmaninoff', 'James Levine', 'Berlin... Piano Concerto No. 3 in D Minor, Op. 30: III. F...         0.982  ...  1921
['John McCormack']                                 The Wearing of the Green                                   0.996  ...  1921
['Sergei Rachmaninoff', 'James Levine', 'Berlin... Piano Concerto No. 3 in D Minor, Op. 30: III. F...         0.982  ...  1921
['Phil Regan']                                     When Irish Eyes Are Smiling                                0.957  ...  1921

[5 rows x 15 columns]

In [ ]:
data.head(3)

                                                                                                       acousticness  ...  year
artists                                            name                                                              ...
['Dennis Day']                                     Clancy Lowered the Boom                                    0.732  ...  1921
['Sergei Rachmaninoff', 'James Levine', 'Berlin... Piano Concerto No. 3 in D Minor, Op. 30: III. F...         0.982  ...  1921
['John McCormack']                                 The Wearing of the Green                                   0.996  ...  1921

[3 rows x 15 columns]

In [ ]:
data.tail ()

                                                acousticness  ...  year
artists                  name                                 ...
['Kelly Clarkson']       Born to Die                  0.6430  ...  2020
['JoJo']                 Man                          0.6700  ...  2020
['S.J Morgan']           Rivers                       0.9790  ...  2020
['Childish Gambino']     0.00                         0.6720  ...  2020
['Alina Baraz', '6LACK'] Morocco (feat. 6LACK)        0.0686  ...  2020

[5 rows x 15 columns]

In [ ]:
data.describe()

        acousticness   danceability  ...        valence           year
count  168592.000000  168592.000000  ...  168592.000000  168592.000000
mean        0.501360       0.533648  ...       0.528497    1977.457774
std         0.377993       0.175919  ...       0.264457      25.406757
min         0.000000       0.000000  ...       0.000000    1921.000000
25%         0.097800       0.412000  ...       0.315000    1957.000000
50%         0.515000       0.543000  ...       0.539000    1978.000000
75%         0.896000       0.662000  ...       0.749000    1999.000000
max         0.996000       0.988000  ...       1.000000    2020.000000

[8 rows x 14 columns]

In [ ]:
data.dtypes

acousticness        float64
danceability        float64
duration_ms           int64
energy              float64
explicit              int64
instrumentalness    float64
liveness            float64
loudness            float64
mode                  int64
popularity            int64
release_date         object
speechiness         float64
tempo               float64
valence             float64
year                  int64
dtype: object

In [ ]:
data.shape

(168592, 15)

In [ ]:
data.size

2528880

In [ ]:
data.groupby('year').aggregate({'duration_ms':'mean'}).head()

        duration_ms
year
1921  229911.914062
1922  167904.541667
1923  178356.301775
1924  184891.512712
1925  184130.699620

In [ ]:
data.iloc[0:5,0:3]

                                                                                                       acousticness  ...  duration_ms
artists                                            name                                                              ...
['Dennis Day']                                     Clancy Lowered the Boom                                    0.732  ...       180533
['Sergei Rachmaninoff', 'James Levine', 'Berlin... Piano Concerto No. 3 in D Minor, Op. 30: III. F...         0.982  ...       831667
['John McCormack']                                 The Wearing of the Green                                   0.996  ...       159507
['Sergei Rachmaninoff', 'James Levine', 'Berlin... Piano Concerto No. 3 in D Minor, Op. 30: III. F...         0.982  ...       831667
['Phil Regan']                                     When Irish Eyes Are Smiling                                0.957  ...       166693

[5 rows x 3 columns]

In [ ]:
data.iloc [[0, 3, 5], [0, 3, -1]]

                                                                                                       acousticness  ...  year
artists                                            name                                                              ...
['Dennis Day']                                     Clancy Lowered the Boom                                    0.732  ...  1921
['Sergei Rachmaninoff', 'James Levine', 'Berlin... Piano Concerto No. 3 in D Minor, Op. 30: III. F...         0.982  ...  1921
['Phil Regan']                                     Come Back To Erin                                          0.957  ...  1921

[3 rows x 3 columns]

In [ ]:
data.iloc[:,-3:-1].head()

                                                                                                         tempo  valence
artists                                            name
['Dennis Day']                                     Clancy Lowered the Boom                              60.936   0.9630
['Sergei Rachmaninoff', 'James Levine', 'Berlin... Piano Concerto No. 3 in D Minor, Op. 30: III. F...   80.954   0.0594
['John McCormack']                                 The Wearing of the Green                             66.221   0.4060
['Sergei Rachmaninoff', 'James Levine', 'Berlin... Piano Concerto No. 3 in D Minor, Op. 30: III. F...   80.954   0.0594
['Phil Regan']                                     When Irish Eyes Are Smiling                         101.665   0.2530

In [ ]:
type(data.iloc[:,-3:-1] )

pandas.core.frame.DataFrame

In [ ]:
data.iloc[:,0].head()

artists                                                             name
['Dennis Day']                                                      Clancy Lowered the Boom                                             0.732
['Sergei Rachmaninoff', 'James Levine', 'Berliner Philharmoniker']  Piano Concerto No. 3 in D Minor, Op. 30: III. Finale. Alla breve    0.982
['John McCormack']                                                  The Wearing of the Green                                            0.996
['Sergei Rachmaninoff', 'James Levine', 'Berliner Philharmoniker']  Piano Concerto No. 3 in D Minor, Op. 30: III. Finale. Alla breve    0.982
['Phil Regan']                                                      When Irish Eyes Are Smiling                                         0.957
Name: acousticness, dtype: float64

In [ ]:
type(data.iloc[:,0] )

pandas.core.series.Series

In [ ]:
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [ ]:
my_series_1 = pd.Series([1,2,3], index=['Tom','Tim',	'Sam'])
my_series_1

Tom    1
Tim    2
Sam    3
dtype: int64

In [ ]:
my_series_2 = pd.Series([4,5,6], index=['Tom',	'Tim',	'Sam'])
my_series_2

Tom    4
Tim    5
Sam    6
dtype: int64

In [ ]:
pd.DataFrame({'col 1':my_series_1	, 'col 2':my_series_2})

     col 1  col 2
Tom      1      4
Tim      2      5
Sam      3      6

In [ ]:
type(data['year'] )

pandas.core.series.Series

In [ ]:
type(data[['year']])

pandas.core.frame.DataFrame

In [ ]:
data.release_date = pd.to_datetime(data.release_date, yearfirst=True) 
data.release_date = data.release_date.dt.year

In [ ]:
data.head(3)

                                                                                                       acousticness  ...  year
artists                                            name                                                              ...
['Dennis Day']                                     Clancy Lowered the Boom                                    0.732  ...  1921
['Sergei Rachmaninoff', 'James Levine', 'Berlin... Piano Concerto No. 3 in D Minor, Op. 30: III. F...         0.982  ...  1921
['John McCormack']                                 The Wearing of the Green                                   0.996  ...  1921

[3 rows x 15 columns]